version: '3.9'

services:
  gameserver:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}  # default to Dockerfile (dev)
    ports:
      - "4000:4000"
      - "4001:4001"
    working_dir: /app
    command: ["sh", "./start-servers.sh"]
    user: node
